-- Sample Data Inserts for Agent Forge State Generator
-- Insert statements for workflow_rows and workflow_blocks_rows tables

-- Insert sample workflow_rows data
INSERT INTO public.workflow_rows (
    id, user_id, workspace_id, folder_id, name, description, color, variables, is_published, created_at, updated_at
) VALUES 
(
    'wf_001', 
    'user_123', 
    'ws_456', 
    NULL, 
    'Trading Bot Workflow', 
    'Automated cryptocurrency trading with risk management', 
    '#FF6B6B', 
    '{"TRADING_PAIR": "BTC/USD", "STOP_LOSS": -5, "TAKE_PROFIT": 10}',
    false,
    '2024-01-04 10:00:00',
    '2024-01-04 10:00:00'
),
(
    'wf_002', 
    'user_123', 
    'ws_456', 
    NULL, 
    'Lead Generation System', 
    'Automated lead capture and qualification pipeline', 
    '#4ECDC4', 
    '{"LEAD_SOURCE": "website", "QUALIFICATION_THRESHOLD": 7}',
    false,
    '2024-01-04 11:00:00',
    '2024-01-04 11:00:00'
),
(
    'wf_003', 
    'user_789', 
    'ws_789', 
    NULL, 
    'Multi-Agent Research Team', 
    'Collaborative AI agents for comprehensive research tasks', 
    '#9B59B6', 
    '{"RESEARCH_TOPIC": "Market Analysis", "AGENT_COUNT": 4}',
    true,
    '2024-01-04 12:00:00',
    '2024-01-04 12:00:00'
);

-- Insert sample workflow_blocks_rows data
INSERT INTO public.workflow_blocks_rows (
    id, workflow_id, type, name, position_x, position_y, enabled, horizontal_handles, 
    is_wide, advanced_mode, height, sub_blocks, outputs, data, parent_id, extent
) VALUES 
-- Trading Bot Workflow Blocks
(
    'block_001', 
    'wf_001', 
    'starter', 
    'Market Monitor', 
    100, 
    100, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"startWorkflow": "schedule", "scheduleType": "interval", "interval": "1m"}',
    '{"success": "block_002"}',
    '{}',
    NULL,
    NULL
),
(
    'block_002', 
    'wf_001', 
    'api', 
    'Fetch Price Data', 
    300, 
    100, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"url": "https://api.binance.com/api/v3/ticker/price", "method": "GET", "params": {"symbol": "BTCUSDT"}}',
    '{"success": "block_003", "error": "block_006"}',
    '{}',
    NULL,
    NULL
),
(
    'block_003', 
    'wf_001', 
    'agent', 
    'Trading Decision Agent', 
    500, 
    100, 
    true, 
    true, 
    false, 
    true, 
    120, 
    '{"model": "gpt-4", "systemPrompt": "Analyze market data and make trading decisions based on technical indicators", "temperature": 0.3}',
    '{"buy": "block_004", "sell": "block_005", "hold": "block_001"}',
    '{}',
    NULL,
    NULL
),
(
    'block_004', 
    'wf_001', 
    'api', 
    'Execute Buy Order', 
    700, 
    50, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"url": "https://api.binance.com/api/v3/order", "method": "POST", "headers": {"X-MBX-APIKEY": "{{env.BINANCE_API_KEY}}"}}',
    '{"success": "block_007"}',
    '{}',
    NULL,
    NULL
),
(
    'block_005', 
    'wf_001', 
    'api', 
    'Execute Sell Order', 
    700, 
    150, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"url": "https://api.binance.com/api/v3/order", "method": "POST", "headers": {"X-MBX-APIKEY": "{{env.BINANCE_API_KEY}}"}}',
    '{"success": "block_007"}',
    '{}',
    NULL,
    NULL
),

-- Lead Generation Workflow Blocks
(
    'block_101', 
    'wf_002', 
    'starter', 
    'Lead Capture', 
    100, 
    100, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"startWorkflow": "webhook", "webhookPath": "/lead-capture", "method": "POST"}',
    '{"success": "block_102"}',
    '{}',
    NULL,
    NULL
),
(
    'block_102', 
    'wf_002', 
    'agent', 
    'Lead Qualifier Agent', 
    300, 
    100, 
    true, 
    true, 
    false, 
    true, 
    120, 
    '{"model": "gpt-4", "systemPrompt": "Qualify leads based on company size, budget, and needs. Score from 1-10.", "temperature": 0.5}',
    '{"qualified": "block_103", "unqualified": "block_105"}',
    '{}',
    NULL,
    NULL
),
(
    'block_103', 
    'wf_002', 
    'api', 
    'Save to CRM', 
    500, 
    100, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"url": "https://api.hubspot.com/contacts/v1/contact", "method": "POST", "headers": {"Authorization": "Bearer {{env.HUBSPOT_TOKEN}}"}}',
    '{"success": "block_104"}',
    '{}',
    NULL,
    NULL
),
(
    'block_104', 
    'wf_002', 
    'output', 
    'Notify Sales Team', 
    700, 
    100, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"outputType": "email", "channels": ["sales@company.com"], "template": "new_qualified_lead"}',
    '{}',
    '{}',
    NULL,
    NULL
),

-- Multi-Agent Research Workflow Blocks
(
    'block_201', 
    'wf_003', 
    'starter', 
    'Research Request', 
    100, 
    200, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"startWorkflow": "manual", "inputFields": ["research_topic", "depth_level"]}',
    '{"success": "block_202"}',
    '{}',
    NULL,
    NULL
),
(
    'block_202', 
    'wf_003', 
    'agent', 
    'Research Coordinator', 
    300, 
    200, 
    true, 
    true, 
    false, 
    true, 
    120, 
    '{"model": "gpt-4", "systemPrompt": "Break down research topics into subtasks for specialized agents", "temperature": 0.6}',
    '{"data_research": "block_203", "trend_analysis": "block_204"}',
    '{}',
    NULL,
    NULL
),
(
    'block_203', 
    'wf_003', 
    'agent', 
    'Data Researcher', 
    500, 
    100, 
    true, 
    true, 
    false, 
    true, 
    120, 
    '{"model": "claude-3-sonnet", "systemPrompt": "Gather and analyze quantitative data and statistics", "temperature": 0.4}',
    '{"complete": "block_205"}',
    '{}',
    NULL,
    NULL
),
(
    'block_204', 
    'wf_003', 
    'agent', 
    'Trend Analyst', 
    500, 
    300, 
    true, 
    true, 
    false, 
    true, 
    120, 
    '{"model": "gemini-pro", "systemPrompt": "Identify trends and patterns in the research domain", "temperature": 0.5}',
    '{"complete": "block_205"}',
    '{}',
    NULL,
    NULL
),
(
    'block_205', 
    'wf_003', 
    'agent', 
    'Report Synthesizer', 
    700, 
    200, 
    true, 
    true, 
    false, 
    true, 
    120, 
    '{"model": "gpt-4", "systemPrompt": "Synthesize research findings into comprehensive report", "temperature": 0.3}',
    '{"complete": "block_206"}',
    '{}',
    NULL,
    NULL
),
(
    'block_206', 
    'wf_003', 
    'output', 
    'Deliver Report', 
    900, 
    200, 
    true, 
    true, 
    false, 
    false, 
    80, 
    '{"outputType": "webhook", "url": "{{env.REPORT_WEBHOOK}}", "format": "markdown"}',
    '{}',
    '{}',
    NULL,
    NULL
); 